gitee:
  oauth:
    clientid:# 需要自己到 阿里云仓库获取 
    clientsecret: # 需要自己到 阿里云仓库获取 
    callback: http://auth.gulimall.com/oauth2.0/gitee/tonken
spring:
  session:
    store-type: redis
  activemq:
    close-timeout: 30m
