server:
  port: 40000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
  redis:
    host: 192.168.111.100


gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
#management:
#  endpoints:
#    jmx:
#      exposure:
#        include: *